#!/bin/bash

host=$1

# Perform some sanity checks
if [ "$host" = "" ]; then
    echo "Please specify host [user@]example.com"
    exit 0
fi

# Check if port is already used
port_open=`netstat -ano tcp | grep 6667`
if [ "$port_open" != "" ]; then
    echo "Port 6667 is already open..."
    echo "> netstat -atlnp | grep 6667"
    echo $port_open
    exit 0
fi

# Start the listener in background
./irssi-notification-listener.sh &

# Start a SSH session to the remote Irssi box
ssh -R 6667:localhost:6667 $1

# Clean up the listener
./kill-subprocs.sh $$
